version : '3'

services:
  db:
    image : mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - dbmongo:/data/db
  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGOURI : mongodb://db/db_ecommerce
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
  react:
    stdin_open : true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./frontend
    ports:
      - "80:5173"
    depends_on:
      - api

volumes:
  dbmongo: